version: 1
logs:
  - index: example
    discovery:
      type: file
      location: .local/config/logs
  - index: infrastructure
    discovery:
      type: file
      location: .local/config/logs
  - index: internal
    discovery:
      type: file
      location: .local/config/logs
  - index: clickhouse
    discovery:
      type: file
      location: .local/config/logs