version: '3'
services:
  opendistro-es:
    image: opensearchproject/opensearch:latest
    container_name: opendistro-es
    environment:
      - cluster.name=odfe-cluster
      - node.name=odfe-node1
      - discovery.seed_hosts=odfe-node1
      - cluster.initial_master_nodes=odfe-node1
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - network.host=0.0.0.0
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - odfe-data:/usr/share/opensearch/data
    ports:
      - 9200:9200
#      - 9600:9600 # required for Performance Analyzer
    networks:
      - odfe-net

  opendistro-dashboards:
    image: opensearchproject/opensearch-dashboards:latest
    container_name: opendistro-dashboards
    depends_on:
      - opendistro-proxy
      - opendistro-es
    ports:
      - 5601:5601
    environment:
      - OPENSEARCH_URL=http://opendistro-proxy:6600
      - OPENSEARCH_HOSTS=http://opendistro-proxy:6600
      - OPENSEARCH_DASHBOARDS_BASE_PATH=/
      - OPENSEARCH_DASHBOARDS_SERVER_BASEPATH=/
    networks:
      - odfe-net

  opendistro-proxy:
    image: moaddib666/opendistro-proxy:1.13.2
    container_name: opendistro-proxy
    user: ${UID}
    environment:
      - ELASTICSEARCH_URL=https://opendistro-es:9200
    build:
        context: ${PWD}
        dockerfile: infrastrcuture/docker/Dockerfile
    depends_on:
      - opendistro-es
    ports:
      - 6200:6200
    volumes:
      - ${PWD}/.local:/app/.local
    networks:
      - odfe-net

  opendistro-shard:
    image: moaddib666/opendistro-proxy:1.13.2
    container_name: opendistro-shard
    entrypoint: /app/shard
    user: ${UID}
    environment:
      - WEBSOCKET_DSN=ws://opendistro-proxy:8080/
    depends_on:
      - opendistro-proxy
    volumes:
      - ${PWD}/.local:/app/.local
    networks:
      - odfe-net

  clickhouse-shard:
    image: clickhouse/clickhouse-server:latest
    hostname: clickhouse-shard
    container_name: clickhouse-shard
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "8123:8123" # HTTP interface shard
      - "9000:9000" # Native client interface shard
    volumes:
      - clickhouse_shard_data:/var/lib/clickhouse
      - ${PWD}/infrastrcuture/docker/clickhouse/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
      - ${PWD}/examples/test.log:/tmp/test.log
    environment:
      CLICKHOUSE_DB: logs
      CLICKHOUSE_USER: default
      CLICKHOUSE_PASSWORD: "default"
      INITIAL_DATA_PATH: /tmp/test.log
    networks:
      - odfe-net

  loki:
    image: grafana/loki:latest
    ports:
      - "3100:3100"
    volumes:
      - loki-data:/loki
      - ${PWD}/infrastrcuture/docker/loki/loki-config.yaml:/etc/loki/local-config.yaml

volumes:
  odfe-data:
  clickhouse_shard_data:
  loki-data:
networks:
  odfe-net:
